#!/usr/bin/env python3
"""
Command line executable allowing to update source files given a IDC index version.
"""

from __future__ import annotations

import argparse
import contextlib
import os
import re
import textwrap
from pathlib import Path

ROOT_DIR = Path(__file__).parent / "../.."


@contextlib.contextmanager
def _log(txt, verbose=True):
    if verbose:
        print(txt)  # noqa: T201
    yield
    if verbose:
        print(f"{txt} - done")  # noqa: T201


def _update_file(filepath, regex, replacement):
    rel_path = os.path.relpath(str(filepath), ROOT_DIR)
    msg = f"Updating {rel_path}"
    with _log(msg):
        pattern = re.compile(regex)
        with filepath.open() as doc_file:
            lines = doc_file.readlines()
            updated_content = []
            for line in lines:
                updated_content.append(re.sub(pattern, replacement, line))
        with filepath.open("w") as doc_file:
            doc_file.writelines(updated_content)


def update_pyproject_toml(idc_index_version):
    """Update pyproject.toml - no longer needed with hatch-vcs.

    Version is now managed via git tags, not pyproject.toml.
    This function is kept for backward compatibility but does nothing.
    """


def update_sql_scripts(idc_index_version):
    """Update all SQL files to use the new IDC version.

    Updates two types of patterns:
    1. idc_vNN in most SQL files (e.g., idc_v23 → idc_v24)
    2. DECLARE latest_idc_version INT64 DEFAULT NN; in prior_versions_index.sql
    """
    # Pattern 1: Update idc_vNN in all SQL files except prior_versions_index.sql
    idc_pattern = re.compile(r"idc_v\d+")
    idc_replacement = f"idc_v{idc_index_version}"

    # Update all .sql files in scripts/sql except prior_versions_index.sql
    sql_dir = ROOT_DIR / "scripts" / "sql"
    for sql_file in sql_dir.glob("*.sql"):
        if sql_file.name != "prior_versions_index.sql":
            _update_file(sql_file, idc_pattern, idc_replacement)

    # Update all .sql files in assets
    assets_dir = ROOT_DIR / "assets"
    if assets_dir.exists():
        for sql_file in assets_dir.glob("*.sql"):
            _update_file(sql_file, idc_pattern, idc_replacement)

    # Pattern 2: Update latest_idc_version in prior_versions_index.sql
    prior_versions_file = sql_dir / "prior_versions_index.sql"
    if prior_versions_file.exists():
        version_pattern = re.compile(r"DECLARE latest_idc_version INT64 DEFAULT \d+;")
        version_replacement = (
            f"DECLARE latest_idc_version INT64 DEFAULT {idc_index_version};"
        )
        _update_file(prior_versions_file, version_pattern, version_replacement)


def update_tests(idc_index_version):
    pattern = re.compile(r"EXPECTED_IDC_INDEX_VERSION = \d+")
    replacement = f"EXPECTED_IDC_INDEX_VERSION = {idc_index_version}"
    _update_file(ROOT_DIR / "tests/test_package.py", pattern, replacement)


def update_version_file(idc_index_version):
    """Update version file - no longer needed with hatch-vcs.

    Version is now auto-generated by hatch-vcs from git tags.
    This function is kept for backward compatibility but does nothing.
    """


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "idc_index_version",
        metavar="IDC_INDEX_VERSION",
        type=int,
        help="IDC index version of the form NN",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Hide the output",
    )

    args = parser.parse_args()

    update_pyproject_toml(args.idc_index_version)
    update_version_file(args.idc_index_version)
    update_sql_scripts(args.idc_index_version)
    update_tests(args.idc_index_version)

    if not args.quiet:
        msg = """\
            Complete! Now run:

            git switch -c update-to-idc-index-{release}
            git add -u scripts/sql/ assets/ tests/test_package.py
            git commit -m "Update to IDC index {release}"
            git tag -a {release}.0.0 -m "Update to IDC index {release}"
            gh pr create --fill --body "Created by update_idc_index_version.py"
            """
        print(textwrap.dedent(msg.format(release=args.idc_index_version)))  # noqa: T201


if __name__ == "__main__":
    main()
